### ISSUE TITLE
Subindex and supindex

### ISSUE THREAD

**Issue by manuel-rubio** [RobertDober/earmark_parser#108]
It looks like there's no support for subindex and superindex in Earmark, as far as I was reading there are two ways for implementing it, the first one is the HTML way:

```
H<sub>2</sub>O
O(n<sup>2</sup>)
```

The other is which was implemented for some Markdown flavors:

```
H~2~O
O(n^2^)
```

The last one is my favorite one, enclosing the element to be superindex or subindex with "^" or  "~" respectively. Could it be implemented?

**Comment by RobertDober** [comment]
I am afraid not

there are not many implementations for it https://babelmark.github.io/?text=H~2~O%0AO(n%5E2%5E)%0A and
implementing it would also mean introducing backward incompatibilities

**Comment by RobertDober** [comment]
merged into branch https://github.com/RobertDober/earmark_parser/tree/i108-sub-and-sup where its functionality will be enabled with the option `sub_sup: true`

**Comment by RobertDober** [comment]
Released c.f. https://elixirforum.com/t/earmark-elixirs-markdown-converter/25208/104
