### ISSUE TITLE
Parse html in headline

### ISSUE THREAD

**Issue by LostKobrakai** [RobertDober/earmark_parser#118]
https://babelmark.github.io/?text=%23%23%23+Initialenkurs+%3Csmall%3E%7C+Bild+1+%2B+2%3C%2Fsmall%3E

Currently the html tags are escaped, while most implementations show this as valid with the html tags used as html

**Comment by RobertDober** [comment]
HTML is only parsed if it is in its own line. But please refer to #7 for future plans
