### ISSUE TITLE
Compilation fails with Elixir 1.15 on CentOS/OEL 7

### ISSUE THREAD

**Issue by kerryb** [RobertDober/earmark_parser#130]
Compilation fails on both CentOS7 and OEL7 after upgrading from Elixir 1.14.5 to 1.15.4, with no other changes. This is the case under both OTP 25 and 26.

[This test project](https://github.com/kerryb/earmark_parser_elixir_1_15_issue) reproduces the error in a Docker container.

## Environment

**OS:** CentOS 7 or OEL7
**OTP:** 25.3 or 26.0.2
**Elixir:** 1.15.4

## Compilation output

```
could not compile dependency :earmark_parser, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile earmark_parser --force", update it with "mix deps.update earmark_parser" or clean it with "mix deps.clean earmark_parser"
** (ErlangError) Erlang error: {:notsup, {~c"hash.c", 112}, ~c"Digest type not supported in this cryptolib"}
    (crypto 5.2) crypto.erl:2200: :crypto.hash(:blake2b, "defmodule EarmarkParser.Ast.Emitter do\n  @moduledoc false\n\n  def emit(tag, content \\\\ [], atts \\\\ [], meta \\\\ %{})\n  def emit(tag, content, atts, meta) when is_binary(content) or is_tuple(content) do\n    {tag, _to_atts(atts), [content], meta}\n  end\n  def emit(tag, content, atts, meta) do\n    {tag, _to_atts(atts), content, meta}\n  end\n\n\n  defp _to_atts(atts)\n  defp _to_atts(nil), do: []\n  defp _to_atts(atts) when is_map(atts) do\n    atts\n    |> Enum.into([])\n    |> Enum.map(fn {name, value} -> {to_string(name), _to_string(value)} end)\n  end\n  defp _to_atts(atts) do\n    atts\n    |> Enum.map(fn {name, value} -> {to_string(name), _to_string(value)} end)\n  end\n\n  defp _to_string(value)\n  defp _to_string(value) when is_list(value), do: Enum.join(value, \" \")\n  defp _to_string(value), do: to_string(value)\nend\n# SPDX-License-Identifier: Apache-2.0\n")
```

**Comment by RobertDober** [comment]
Not sure I can help with this, but I'll try with the limitted resources I have

Thankx for the report

**Comment by kerryb** [comment]
> Not sure I can help with this, but I'll try with the limitted resources I have

Thank you! I’ll keep digging, and if I get anywhere I’ll try to put a PR together.

**Comment by kerryb** [comment]
Looks like the error is actually with [html_entities](https://github.com/martinsvalin/html_entities). I’ll raise an issue/PR there instead – feel free to close this one!

**Comment by kerryb** [comment]
> Looks like the error is actually with [html_entities](https://github.com/martinsvalin/html_entities). I’ll raise an issue/PR there instead – feel free to close this one!

Actually it seems both libraries are red herrings – it looks like a problem with the Elixir compiler itself on that platform (I guess there’s something it relies on that’s not installed by default), and it was just down to the order it chose to compile things that the error always happened while compiling those dependencies. Sorry for having wasted your time!

**Comment by RobertDober** [comment]
You did not waste my time, but I was afraid this was yet another problem with RedHat. 

Take care
