### ISSUE TITLE
Extraneous Illegal attributes ignored in IAL warning

### ISSUE THREAD

**Issue by wojtekmach** [RobertDober/earmark_parser#21]
I don't know enough about the spec/implementation to say if the warning is appropriate but I thought I'd mention this anyway:

```elixir
iex> EarmarkParser.as_ast("{:ok, status, %MyApp.User{}} on success")
{:error, [{"p", [], ["} on success"], %{}}],
 [
   {:warning, 1,
    "Illegal attributes [\"%MyApp.User{\", \"status,\", \"ok,\"] ignored in IAL"}
 ]}
```

Ref https://github.com/elixir-lang/ex_doc/issues/1222#issuecomment-660875046

**Comment by RobertDober** [comment]
This is parsed _"correctly"_ in the sense that this is an IAL, an extension that Earmark supports by default (and cannot be switched off either, right now)

the description is here https://github.com/RobertDober/earmark_parser#adding-attributes-with-the-ial-extension

Seems to be confusing for some folk right now, after it lay dormant for years, strange...

Of course escaping the first accolade does the trick:

```elixir
iex(3)> as_ast("\\{:ok, status, %MyApp.User{}} on success")
{:ok, [{"p", [], ["{:ok, status, %MyApp.User{}} on success"], %{}}], []}
```

**Comment by RobertDober** [comment]
If this is bothering we can maybe deactivate it after whitespace (meaning also after a blank line) or by options.

However that would be low priority from my POV.

For reference https://github.com/pragdave/earmark/issues/380

**Comment by wojtekmach** [comment]
IMHO not a big deal either, thanks!
