### ISSUE TITLE
Spaces missing before links

### ISSUE THREAD

**Issue by RobertDober** [RobertDober/earmark_parser#22]
https://github.com/pragdave/earmark/issues/382

When I pass a string like `*Test* https://www.google.com` into the `as_html` function, I get back a result that doesn't have spacing:

Here is an example with many spaces added:

```
iex(12)> Earmark.as_html!("**Test**          https://www.google.com")
"<p>\n<strong>Test</strong><a href=\"https://www.google.com\">https://www.google.com</a></p>\n"
```

If the first element is just simple text, it includes the spaces:

```
iex(13)> Earmark.as_html!("Test          https://www.google.com")    
"<p>\nTest          <a href=\"https://www.google.com\">https://www.google.com</a></p>\n"
```

**Comment by eksperimental** [comment]
I came to create an issue and I found this one. It happens before custom links.

```elixir
iex(7)> EarmarkParser.as_ast("`Warnings.bar/0`  [x](`Warning`)")
{:ok,
 [
   {"p", [],
    [ 
      {"code", [{"class", "inline"}], ["Warnings.bar/0"], %{}},
      {"a", [{"href", "`Warning`"}], ["x"], %{}}
    ], %{}}
 ], []}
```

**Comment by RobertDober** [comment]
Thank you for the info.

**Comment by sionide21** [comment]
I can take this if you want. I think I know what the problem is.
