### ISSUE TITLE
Side by side reference style links not working 

### ISSUE THREAD

**Issue by kianmeng** [RobertDober/earmark_parser#28]
Not sure this is a bug or missing configuration. But side by side reference style links not working as intended while adjusting the HTML doc for https://github.com/OldhamMade/TeslaCacher/pull/1.

Sample markdown.

```
[![Build Status](https://travis-ci.org/OldhamMade/TeslaCacher.svg?branch=main)][TravisCI] 
[![Module Version](https://img.shields.io/hexpm/v/tesla_cacher.svg)][ModuleVersion]

...

[TravisCI]: https://travis-ci.org/OldhamMade/TeslaCacher
[ModuleVersion]: https://hex.pm/packages/tesla_cacher 
```

Expected (as rendered in VSCode).

![image](https://user-images.githubusercontent.com/134518/97992771-1aa7f880-1e1e-11eb-9487-6c30367a4f74.png)

Actual (as generated by EarMarkParser through ex_doc).

![image](https://user-images.githubusercontent.com/134518/97992747-1380ea80-1e1e-11eb-95bb-160837ee8b30.png)

**Comment by RobertDober** [comment]
I was not aware of this syntax and it seems almost nobody else is :wink:

https://babelmark.github.io/?text=%5BTravisCI%5D%3A+https%3A%2F%2Ftravis-ci.org%2FOldhamMade%2FTeslaCacher%0A%5BModuleVersion%5D%3A+https%3A%2F%2Fhex.pm%2Fpackages%2Ftesla_cacher+%0A

**Comment by kianmeng** [comment]
You have to include the full example.

https://babelmark.github.io/?text=%5B!%5BBuild+Status%5D(https%3A%2F%2Ftravis-ci.org%2FOldhamMade%2FTeslaCacher.svg%3Fbranch%3Dmain)%5D%5BTravisCI%5D+%0A%5B!%5BModule+Version%5D(https%3A%2F%2Fimg.shields.io%2Fhexpm%2Fv%2Ftesla_cacher.svg)%5D%5BModuleVersion%5D%0A%0A...%0A%0A%5BTravisCI%5D%3A+https%3A%2F%2Ftravis-ci.org%2FOldhamMade%2FTeslaCacher%0A%5BModuleVersion%5D%3A+https%3A%2F%2Fhex.pm%2Fpackages%2Ftesla_cacher+

![image](https://user-images.githubusercontent.com/134518/98118574-645c1600-1ee6-11eb-8877-341c0afca003.png)

**Comment by RobertDober** [comment]
I really have to look at this. Ad hoc I do not believe this is an error but in order to check I would like you to give me the expected html output, images are just not very useful. Thanx

**Comment by myrrlyn** [comment]
I am encountering behavior similar to this. [Babelmark link](https://babelmark.github.io/?text=Correct%0A%0A%5B!%5B%5D(https%3A%2F%2Fimg.shields.io%2Fcrates%2Fv%2Fcalm_io.svg)%5D(https%3A%2F%2Fcrates.io%2Fcrates%2Fcalm_io)%0A%5B!%5B%5D(https%3A%2F%2Fdocs.rs%2Fcalm_io%2Fbadge.svg)%5D(https%3A%2F%2Fdocs.rs%2Fcalm_io)%0A%5B!%5B%5D(https%3A%2F%2Fimg.shields.io%2Fcrates%2Fl%2Fcalm_io.svg)%5D(https%3A%2F%2Fgithub.com%2Fmyrrlyn%2Fcalm_io%2Fblob%2Fmaster%2FLICENSE.txt)%0A%5B!%5B%5D(https%3A%2F%2Fimg.shields.io%2Fcrates%2Fdv%2Fcalm_io.svg)%5D(https%3A%2F%2Fcrates.io%2Fcrates%2Fcalm_io)%0A%5B!%5B%5D(https%3A%2F%2Ftokei.rs%2Fb1%2Fgithub%2Fmyrrlyn%2Fcalm_io%3Fcategory%3Dcode)%5D(https%3A%2F%2Fgithub.com%2Fmyrrlyn%2Fcalm_io)%0A%0AIncorrect%0A%0A%5B!%5BCrate%5D%5Bcrate_img%5D%5D%5Bcrate%5D%0A%5B!%5BDocumentation%5D%5Bdocs_img%5D%5D%5Bdocs%5D%0A%5B!%5BLicense%5D%5Blicense_img%5D%5D%5Blicense%5D%0A%5B!%5BCrate+Downloads%5D%5Bdl_img%5D%5D%5Bcrate%5D%0A%5B!%5BCrate+Size%5D%5Bloc_img%5D%5D%5Bsource%5D%0A%0A%5Bcrate%5D%3A+++++++https%3A%2F%2Fcrates.io%2Fcrates%2Fcalm_io+%22Crate+Link%22%0A%5Bcrate_img%5D%3A+++https%3A%2F%2Fimg.shields.io%2Fcrates%2Fv%2Fcalm_io.svg+%22Crate+Version+Display%22%0A%5Bdl_img%5D%3A++++++https%3A%2F%2Fimg.shields.io%2Fcrates%2Fdv%2Fcalm_io.svg+%22Download+Counter%22%0A%5Bdocs%5D%3A++++++++https%3A%2F%2Fdocs.rs%2Fcalm_io+%22Documentation+Link%22%0A%5Bdocs_img%5D%3A++++https%3A%2F%2Fdocs.rs%2Fcalm_io%2Fbadge.svg+%22Documentation+Display%22%0A%5Blicense%5D%3A+++++https%3A%2F%2Fgithub.com%2Fmyrrlyn%2Fcalm_io%2Fblob%2Fmaster%2FLICENSE.txt+%22License%22%0A%5Blicense_img%5D%3A+https%3A%2F%2Fimg.shields.io%2Fcrates%2Fl%2Fcalm_io.svg+%22License+Display%22%0A%5Bloc_img%5D%3A+++++https%3A%2F%2Ftokei.rs%2Fb1%2Fgithub%2Fmyrrlyn%2Fcalm_io%3Fcategory%3Dcode+%22Repository+Size%22%0A%5Bsource%5D%3A++++++https%3A%2F%2Fgithub.com%2Fmyrrlyn%2Fcalm_io+%22Source+Code%22)

Versions:

- `earmark`: 1.4.14
- `earmark_parser`: 1.4.12

Markdown:

<details>

```md
Correct

[![](https://img.shields.io/crates/v/calm_io.svg)](https://crates.io/crates/calm_io)
[![](https://docs.rs/calm_io/badge.svg)](https://docs.rs/calm_io)
[![](https://img.shields.io/crates/l/calm_io.svg)](https://github.com/myrrlyn/calm_io/blob/master/LICENSE.txt)
[![](https://img.shields.io/crates/dv/calm_io.svg)](https://crates.io/crates/calm_io)
[![](https://tokei.rs/b1/github/myrrlyn/calm_io?category=code)](https://github.com/myrrlyn/calm_io)

Incorrect

[![Crate][crate_img]][crate]
[![Documentation][docs_img]][docs]
[![License][license_img]][license]
[![Crate Downloads][dl_img]][crate]
[![Crate Size][loc_img]][source]

[crate]:       https://crates.io/crates/calm_io "Crate Link"
[crate_img]:   https://img.shields.io/crates/v/calm_io.svg "Crate Version Display"
[dl_img]:      https://img.shields.io/crates/dv/calm_io.svg "Download Counter"
[docs]:        https://docs.rs/calm_io "Documentation Link"
[docs_img]:    https://docs.rs/calm_io/badge.svg "Documentation Display"
[license]:     https://github.com/myrrlyn/calm_io/blob/master/LICENSE.txt "License"
[license_img]: https://img.shields.io/crates/l/calm_io.svg "License Display"
[loc_img]:     https://tokei.rs/b1/github/myrrlyn/calm_io?category=code "Repository Size"
[source]:      https://github.com/myrrlyn/calm_io "Source Code"
```

</details>

Rendered:

<img width="427" alt="rendered" src="https://user-images.githubusercontent.com/5921109/111561561-433fe780-875a-11eb-85b6-3321b44709bb.png">

HTML output:

<details>

```html
<p> Correct </p>
<p>
  <a href="https://crates.io/crates/calm_io"> <img src="https://img.shields.io/crates/v/calm_io.svg" alt=""> </a>
  <a href="https://docs.rs/calm_io"> <img src="https://docs.rs/calm_io/badge.svg" alt=""> </a>
  <a href="https://github.com/myrrlyn/calm_io/blob/master/LICENSE.txt"> <img src="https://img.shields.io/crates/l/calm_io.svg" alt=""> </a>
  <a href="https://crates.io/crates/calm_io"> <img src="https://img.shields.io/crates/dv/calm_io.svg" alt=""> </a>
  <a href="https://github.com/myrrlyn/calm_io"> <img src="https://tokei.rs/b1/github/myrrlyn/calm_io?category=code" alt=""> </a>
</p>
<p> Incorrect </p>
<p>
  <a href="https://github.com/myrrlyn/calm_io" title="Source Code">!</a><a href="https://crates.io/crates/calm_io" title="Crate Link">Crate]</a>
  <a href="https://github.com/myrrlyn/calm_io/blob/master/LICENSE.txt" title="License">crate_img]]</a>
  <a href="https://docs.rs/calm_io" title="Documentation Link">crate]
[  <img src="https://docs.rs/calm_io/badge.svg" alt="Documentation" title="Documentation Display">
</a>
[  <img src="https://img.shields.io/crates/l/calm_io.svg" alt="License" title="License Display">

[  <img src="https://img.shields.io/crates/dv/calm_io.svg" alt="Crate Downloads" title="Download Counter">

[  <img src="https://tokei.rs/b1/github/myrrlyn/calm_io?category=code" alt="Crate Size" title="Repository Size">
</p>
```

</details>

AST output:

<details>

```elixir
{:ok,
 [
   {"p", [], ["Correct"], %{}},
   {"p", [],
    [
      {"a", [{"href", "https://crates.io/crates/calm_io"}],
       [{"img", [{"src", "https://img.shields.io/crates/v/calm_io.svg"}, {"alt", ""}], [], %{}}],
       %{}},
      "\n",
      {"a", [{"href", "https://docs.rs/calm_io"}],
       [{"img", [{"src", "https://docs.rs/calm_io/badge.svg"}, {"alt", ""}], [], %{}}], %{}},
      "\n",
      {"a", [{"href", "https://github.com/myrrlyn/calm_io/blob/master/LICENSE.txt"}],
       [{"img", [{"src", "https://img.shields.io/crates/l/calm_io.svg"}, {"alt", ""}], [], %{}}],
       %{}},
      "\n",
      {"a", [{"href", "https://crates.io/crates/calm_io"}],
       [{"img", [{"src", "https://img.shields.io/crates/dv/calm_io.svg"}, {"alt", ""}], [], %{}}],
       %{}},
      "\n",
      {"a", [{"href", "https://github.com/myrrlyn/calm_io"}],
       [
         {"img",
          [{"src", "https://tokei.rs/b1/github/myrrlyn/calm_io?category=code"}, {"alt", ""}], [],
          %{}}
       ], %{}}
    ], %{}},
   {"p", [], ["Incorrect"], %{}},
   {"p", [],
    [
      {"a", [{"href", "https://github.com/myrrlyn/calm_io"}, {"title", "Source Code"}],
       [
         "!",
         {"a", [{"href", "https://crates.io/crates/calm_io"}, {"title", "Crate Link"}],
          [
            "Crate]",
            {"a",
             [
               {"href", "https://github.com/myrrlyn/calm_io/blob/master/LICENSE.txt"},
               {"title", "License"}
             ],
             [
               "crate_img]]",
               {"a", [{"href", "https://docs.rs/calm_io"}, {"title", "Documentation Link"}],
                [
                  "crate]\n[",
                  {"img",
                   [
                     {"src", "https://docs.rs/calm_io/badge.svg"},
                     {"alt", "Documentation"},
                     {"title", "Documentation Display"}
                   ], [], %{}}
                ], %{}},
               "\n[",
               {"img",
                [
                  {"src", "https://img.shields.io/crates/l/calm_io.svg"},
                  {"alt", "License"},
                  {"title", "License Display"}
                ], [], %{}}
             ], %{}},
            "\n[",
            {"img",
             [
               {"src", "https://img.shields.io/crates/dv/calm_io.svg"},
               {"alt", "Crate Downloads"},
               {"title", "Download Counter"}
             ], [], %{}}
          ], %{}},
         "\n[",
         {"img",
          [
            {"src", "https://tokei.rs/b1/github/myrrlyn/calm_io?category=code"},
            {"alt", "Crate Size"},
            {"title", "Repository Size"}
          ], [], %{}}
       ], %{}}
    ], %{}}
 ], []}
```

</details>

I hope this is sufficient information. Please let me know if there is anything more I can provide. Also, thank you for your work on this library!
