### ISSUE TITLE
Content after <sup> gets discarded

### ISSUE THREAD

**Issue by lexmag** [RobertDober/earmark_parser#31]
To reproduce:
```elixir
EarmarkParser.as_ast(~S"""
<sup>1</sup>`Msgpax.Packer` foo

<sup>2</sup>NaN bar
""")
```

v1.4.12 gives:
```elixir
[
  {"sup", [], ["1"], %{verbatim: true}},
  {"sup", [], ["2"], %{verbatim: true}}
]
```

**Comment by RobertDober** [comment]
Same reasoning as in #30 https://github.com/RobertDober/earmark_parser#html-blocks

**Comment by wojtekmach** [comment]
@RobertDober sorry for piling on, is the following also expected given current implementation? That is we have raw html in the same line but _after_ some markdown.

```elixir
md = """
*foo* <em>bar</em>
"""

Earmark.as_html!(md)
|> IO.puts()
# Outputs:
# <p>
# <em>foo</em> &lt;em&gt;bar&lt;/em&gt;</p>

EarmarkParser.as_ast(md)
|> IO.inspect()
# Outputs:
# {:ok, [{"p", [], [{"em", [], ["foo"], %{}}, " <em>bar</em>"], %{}}], []}
# NOTE: no %{verbatim: true}!

**Comment by RobertDober** [comment]
Yes indeed HTML is only parsed as such if in its own line, I should be working on this, alas, I am very busy looking for a job.

**Comment by RobertDober** [comment]
and no need whatsoever to apologise 😉
