### ISSUE TITLE
Latest version discrepancy 1.4.12 -> 1.5.0

### ISSUE THREAD

**Issue by nikokozak** [RobertDober/earmark_parser#32]
Just a slight discrepancy in the documentation: the latest version in the docs is specified as { :earmark_parser, "\~> 1.5.0" }, but the actual latest available version is "~> 1.4.2".

The lib is fantastic, you're doing god's work here.

**Comment by RobertDober** [comment]
No I am not, but thank you anyway :wink:
Well I push the version as soon as I have released to avoid any accidental override. This is an old habbit but actually unnecessary with hex, maybe I shall not do that in the future as the next version might as well be 1.4.13, I'll think it over...

**Comment by josevalim** [comment]
One option is to specify `~> "1.4"` in the README and now it will work for both future v1.4.x versions and v1.5.x. :)

**Comment by RobertDober** [comment]
I guess it is time to close this one ;)
