### ISSUE TITLE
Parse multiple HTML tags in a single line

### ISSUE THREAD

**Issue by jonatanklosko** [RobertDober/earmark_parser#39]
Given a single line with multiple tag pairs, all except the first one are ignored:

```elixir
iex> EarmarkParser.as_ast("<kbd>Ctrl</kbd>+<kbd>A</kbd>")
{:ok, [{"kbd", [], ["Ctrl"], %{verbatim: true}}], []}
```

The parser shouldn't drop the content, so I think we could either:

* interpret `<tag>...</tag>some more content` as a paragraph (this mirrors the behaviour if the same sequence was in the middle of the text)
* parse such line into multiple AST nodes, like `[{"kbd", [], ["Ctrl"], %{verbatim: true}}, "+", [{"kbd", [], ["A"], %{verbatim: true}}]]`

**Comment by RobertDober** [comment]
Will be fixed with #7
