### ISSUE TITLE
Footnotes don't work when embedded in a list

### ISSUE THREAD

**Issue by michaelforrest** [RobertDober/earmark_parser#40]
This code (parsed with `footnotes: true`, of course):
```
* here is a footnote in a list[^1]

[^1]: my footnote from the list
```

Results in the following AST:

`{"ul", [], [{"li", [], ["here is a footnote in a list[^1]"], %{}}], %{}}`

It's swallowing the footnote content and not creating a link in the list item. 

I thought I'd try to be helpful by starting a [PR](https://github.com/RobertDober/earmark_parser/compare/master...michaelforrest:master) on this but not sure it's useful without a solution! It's gonna be regex hell isn't it...

**Comment by michaelforrest** [comment]
Nice one! 👍👍

**Comment by RobertDober** [comment]
appreciated @michaelforrest
