### ISSUE TITLE
Where does string lexer come from?

### ISSUE THREAD

**Issue by jakubpawlowicz** [RobertDober/earmark_parser#63]
Hello,

Sorry if the answer is obvious, but I'm having trouble with understanding where `:string_lexer` comes from?
Is it an Erlang built-in OTP app?

https://github.com/RobertDober/earmark_parser/blob/b15d9d78c0d916fd09b58ecea590e5b1f355f6cf/lib/earmark_parser/helpers/lookahead_helpers.ex#L17

Thanks,
Jakub

**Comment by RobertDober** [comment]
It's not obvious at all, and I'll gladly answer

I would prefer that kind of question to be asked on the forum, ideally in the [Earmark thread](https://elixirforum.com/t/earmark-elixirs-markdown-converter/25208), but no big deal.

Actually it comes from [src/string_lexer.xrl](https://github.com/RobertDober/earmark_parser/blob/master/src/string_lexer.xrl)

You were on the right track with Erlang, however it is not the string_lexer that is built in but [`leex`](https://www.erlang.org/doc/man/leex.html) and [`yecc`](https://www.erlang.org/doc/man/yecc.html)
which are part of the default compilers in Elixir

therefore you can do the following

```iex
iex(1)> "ab" |> String.to_charlist |> :string_lexer.string()
{:ok, [{:other, 1, 'ab'}], 1}
```

the file https://github.com/RobertDober/earmark_parser/blob/master/lib/earmark_parser/helpers/leex_helpers.ex just contains some _Elixification_ around the lexer.

I guess if I had not imported that helper but used a qualified call to `tokenize`  you would have found out for yourself 
that's what you get from working alone on a project :blush: 

HTH

**Comment by jakubpawlowicz** [comment]
Got it, thanks @RobertDober!
