### ISSUE TITLE
Incorrect line numbering when reference-style links used in lists with items separated by blank lines

### ISSUE THREAD

**Issue by davidsulc** [RobertDober/earmark_parser#65]
# Problem

Minimal case:

```
* top

    * one[][foo]

[foo]: # "bar"
```

(Note: this example uses a link with empty text, but this issue also appears if text is present, i.e. `[x][foo]`.)

Yields:

```elixir
{[
   %EarmarkParser.Block.List{
     annotation: nil,
     attrs: nil,
     blocks: [
       %EarmarkParser.Block.ListItem{
         annotation: nil,
         attrs: nil,
         blocks: [
           %EarmarkParser.Block.Text{
             annotation: nil,
             attrs: nil, 
             line: ["top"],
             lnb: 2
           },
           %EarmarkParser.Block.List{
             annotation: nil,
             attrs: nil,
             blocks: [
               %EarmarkParser.Block.ListItem{
                 annotation: nil,
                 attrs: nil,
                 blocks: [
                   %EarmarkParser.Block.Text{
                     annotation: nil,
                     attrs: nil,
                     line: ["one[][foo]"],
                     lnb: 4
                   }
                 ],
                 bullet: "*",
                 lnb: 4,
                 loose?: false,
                 spaced: false,
                 type: :ul
               }
             ],
             bullet: "*",
             lnb: 4,
             loose?: false,
             start: "",
             type: :ul
           } 
         ],
         bullet: "*",
         lnb: 1,
         loose?: true,
         spaced: false,
         type: :ul
       }
     ],
     bullet: "*",
     lnb: 1,
     loose?: true,
     start: "",
     type: :ul
   },
   %EarmarkParser.Block.IdDef{
     annotation: nil,
     attrs: nil,
     id: "foo",
     lnb: 5,
     title: "bar",
     url: "#"
   }
 ],
 %EarmarkParser.Context{
   footnotes: %{},
   links: %{
     "foo" => %EarmarkParser.Block.IdDef{
       annotation: nil,
       attrs: nil, 
       id: "foo",
       lnb: 5,
       title: "bar",
       url: "#"
     }
   },
   options: %EarmarkParser.Options{
     annotations: nil,
     breaks: false,
     code_class_prefix: nil,
     file: "<no file>",
     footnote_offset: 1,
     footnotes: false,
     gfm: true,
     gfm_tables: false,
     line: 4,
     mapper: &EarmarkParser.pmap/2,
     mapper_with_timeout: &EarmarkParser.pmap/3,
     messages: [],
     parse_inline: true,
     pedantic: false,
     pure_links: true,
     renderer: EarmarkParser.HtmlRenderer,
     smartypants: false,
     timeout: nil,
     wikilinks: false
   },
   rules: %{
     br: ~r/^ {2,}\n(?!\s*$)/,
     escape: ~r/^\\([\\`*\{}\[\]()\#+\-.!_>~|])/,
     footnote: ~r/\z\A/,
     strikethrough: ~r/^~~(?=\S)([\s\S]*?\S)~~/,
     text: ~r/^[\s\S]+?(?=[\\<!\[_*`~]|https?:\/\/| \{2,}\n|$)/,
     url: ~r/^(https?:\/\/[^\s<]+[^<.,:;\"\')\]\s])/
   },
   value: []
 }}
```

The line numbers (`lnb`) for the content are off by 1.

## Apparent cause

(The problem seems to maybe come from https://github.com/RobertDober/earmark_parser/blob/d1cdeb1fbd3b7bdb2f1a9e69150174844856a7f8/lib/earmark_parser/parser/list_parser.ex#L58: it appears the line value should only be incremented during the parsing of the nested list?)

It seems this appears when all of the following are true:

* nested list
* sub-list uses a reference-style link (i.e. `[][foo]`, `[x][foo]`, etc.)
* blank lines are used to separate some list items

The degree to which the line number count drifts is linked to the number of elements in the sub-list that are on that line or below.

Example:

```
* top

    * one[][foo]

    * two

[foo]: # "bar"
```

Here, lines "top" and "one" will be off by 2 (`lnb` at 3 instead of 1, and 5 instead of 3, respectively), while line "two" will be off by 1 (`lnb` at 6 instead of 5). That's because lines "top" and "one" still have 2 elements in the sub list that are on that line or below it, while line "two" has only one such element (itself).

Another example:
```
* top

    * zero

    * one[][foo]

    * two

    * three

[foo]: # "bar"
```

Here's how their line numbers drift:

1. top -> off by 4
1. zero -> off by 4
1. one -> off by 3
1. two -> off by 2
1. three -> off by 1

Finally, these 2 cases also present line number drift, but with a different amount:

```
* top

    * zero

    * one

    * two

    * three

[foo]: # "bar"
```

```
* top

    * zero

    * one[][foo]

    * two

    * three

```

It appears that having the reference-style link present increases the drift by 1.

## Workaround

Not having spaces between list items:

```
* top
    * zero
    * one[][foo]
    * two
    * three

[foo]: # "bar"
```

Hope this was helpful!

**Comment by RobertDober** [comment]
Thank you for this thorrow ticket

This is probably taking a while  as lists are quite broken and I have no short term ETA of fixing them, sorry.

**Comment by RobertDober** [comment]
Relates to #45, #9, #4

**Comment by RobertDober** [comment]
@davidsulc finally found some time to look into this, and turns out to be an easy fix 😊 

you identified the line correctly and it has nothing to do with reference links, just a stupid increment of the line number for each blank line (this can be seen [here](https://github.com/RobertDober/earmark_parser/blob/3bb9cddb4d1bced67064f3d705898d85ebf9f2c4/test/acceptance/regressions/i065-bad-lnb-ref-style.exs#L37)

Thank you again for this report

**Comment by davidsulc** [comment]
Thanks for your work fixing this!

**Comment by RobertDober** [comment]
My pleasure @davidsulc I am always happy when I find the time to work on EarmarkParser :blush:
